version: '3'

services:
  portfolio:
    build: 
      context: ./srcs    # Pointe vers le dossier srcs
      dockerfile: Dockerfile
    container_name: portfolio
    ports:
      - "8080:80"
    restart: unless-stopped