version: '3'

services:
  portfolio:
    build: 
      context: ./srcs    # Pointe vers le dossier srcs
      dockerfile: Dockerfile
    container_name: portfolio
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true